default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: utf8mb4
  collation: utf8mb4_bin
  username: root
  password: Welcome@123

development:
  <<: *default
  database: dev_shop_development
